/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.49
 * Generated at: 2018-05-03 08:34:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages.bs.psonl;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/G:/JAVA/Proj_zhz233/.metadata/.plugins/org.eclipse.wst.server.core/tmp2/wtpwebapps/zhz233/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1521464765704L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("<head>\r\n");
      out.write("    <!-- 设置编码 -->\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <!-- 网页内容描述 -->\r\n");
      out.write("    <meta name=\"description\" content=\"租号站，租号站233，租出好体验租号平台\">\r\n");
      out.write("    <!-- 网页内容关键字 -->\r\n");
      out.write("    <meta name=\"keywords\" content=\"zuzhaozhan233,租号站233,租号站\">\r\n");
      out.write("    <!-- 移动端适配 -->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=on\">\r\n");
      out.write("    <!-- 标题 -->\r\n");
      out.write("    <title>租号站233|——租出好体验的网站</title>\r\n");
      out.write("    <!-- 引入css样式 -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap-grid.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap-reboot.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/zhz233-common.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- top s -->\r\n");
      out.write("<div class=\"container-fluid assist-a\">\r\n");
      out.write("    <div class=\"container \">\r\n");
      out.write("        <div class=\"row assist-a-0\">\r\n");
      out.write("            <div class=\"assist-a-1\">\r\n");
      out.write("                <div class=\"assist-a-1-1 float-left\">\r\n");
      out.write("                    <img src=\"img/bs_assist_logo.png\" alt=\"logo.png\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"assist-a-1-2 float-left\"></div>\r\n");
      out.write("                <div class=\"assist-a-1-3 float-right\">\r\n");
      out.write("                    <a href=\"bspg/home\">首页</a>\r\n");
      out.write("                    <a href=\"bspg/help\">帮助中心</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- top e -->\r\n");
      out.write("<!-- img s -->\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"assist-img\">\r\n");
      out.write("        <img class=\"img-fluid\" src=\"img/bs_assist_bg_1.gif\" alt=\"bg_1.gif\">\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- img e -->\r\n");
      out.write("<!-- login s -->\r\n");
      out.write("<div class=\"container-fluid assist-b\">\r\n");
      out.write("    <div class=\"container \">\r\n");
      out.write("        <div class=\"row assist-b-0\">\r\n");
      out.write("            <div class=\"assist-b-1\">\r\n");
      out.write("                <div class=\"assist-b-1-1\">\r\n");
      out.write("                    <div class=\"assist-b-1-1-1\">\r\n");
      out.write("                        <div class=\"assist-b-1-1-1-1 float-left\">登录</div>\r\n");
      out.write("                        <div class=\"assist-b-1-1-1-2 float-right\"><a href=\"bspg/register\">注册账号</a></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"assist-b-1-1-2\">\r\n");
      out.write("                        <div class=\"assist-b-1-1-2-0\">\r\n");
      out.write("                            <div class=\"assist-b-1-1-2-1-tip\">\r\n");
      out.write("                                <div class=\"assist-b-1-1-2-1-tip-5\" id=\"user_tip\">\r\n");
      out.write("                                    <!--提示：请输入用户名！-->\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-group assist-b-1-1-2-1\">\r\n");
      out.write("                                <lable class=\"btn input-group-append assist-b-1-1-2-1-1\"><span class=\"fa fa-user\"></span></lable>\r\n");
      out.write("                                <input class=\"form-control assist-b-1-1-2-2\" type=\"text\" placeholder=\"用户名\" id=\"input_user\" maxlength=\"12\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"assist-b-1-1-2\">\r\n");
      out.write("                        <div class=\"assist-b-1-1-2-0\">\r\n");
      out.write("                            <div class=\"assist-b-1-1-2-1-tip\">\r\n");
      out.write("                                <div class=\"assist-b-1-1-2-1-tip-5\" id=\"pwd_tip\">\r\n");
      out.write("                                    <!--请输入用户登录密码！-->\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-group assist-b-1-1-2-1\">\r\n");
      out.write("                                <lable class=\"btn input-group-append assist-b-1-1-2-1-1\"><span class=\"fa fa-lock\"></span></lable>\r\n");
      out.write("                                <input class=\"form-control assist-b-1-1-2-2\" type=\"password\" placeholder=\"密码\" id=\"input_pwd\" maxlength=\"12\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"assist-b-1-1-3\">\r\n");
      out.write("                        <div class=\"assist-b-1-1-3-1-tip\">\r\n");
      out.write("                            <div class=\"assist-b-1-1-3-1-tip-1\" id=\"code_tip\">\r\n");
      out.write("                                <!-- 请输入验证码！-->\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"assist-b-1-1-3-0\">\r\n");
      out.write("                            <div class=\"assist-b-1-1-3-1 float-left\">\r\n");
      out.write("                                <div class=\"input-group assist-b-1-1-3-1-1\">\r\n");
      out.write("                                    <input class=\"form-control\" type=\"text\" placeholder=\"验证码\" id=\"input_code\" maxlength=\"4\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"assist-b-1-1-3-2 float-left\">\r\n");
      out.write("                                <div class=\"assist-b-1-1-3-2-1\">\r\n");
      out.write("                                    <span id=\"code_show\"></span>\r\n");
      out.write("                                    <!--<img class=\"img-fluid\" src=\"img/bs_assist_code.png\" alt=\"code.gif\">-->\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"assist-b-1-1-3-3 float-left\">\r\n");
      out.write("                                <div class=\"assist-b-1-1-3-3-1\">\r\n");
      out.write("                                    <span>看不清？|</span>\r\n");
      out.write("                                    <span class=\"assist-b-1-1-3-3-1-1\"  id=\"code_change\">换一张</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"assist-b-1-1-4\">\r\n");
      out.write("                        <div class=\"assist-b-1-1-4-0\">\r\n");
      out.write("                            <div class=\"assist-b-1-1-4-1 float-left\">\r\n");
      out.write("                                <div class=\"input-group assist-b-1-1-4-1-1\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"assist-b-1-1-4-2 float-left\">\r\n");
      out.write("                                <div class=\"assist-b-1-1-4-2-1\">\r\n");
      out.write("                                    <span id=\"btn_back\">忘记密码</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"assist-b-1-1-5\">\r\n");
      out.write("                        <div class=\"assist-b-1-1-5-1-tip\">\r\n");
      out.write("                            <div class=\"assist-b-1-1-5-1-tip-1\" id=\"login_tip\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"btn assist-b-1-1-5-1\" id=\"btn_login\">\r\n");
      out.write("                            立即登录\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- login e -->\r\n");
      out.write("<!-- bottom s -->\r\n");
      out.write("<div class=\"container-fluid assist-c\">\r\n");
      out.write("    <div class=\"container \">\r\n");
      out.write("        <div class=\"row assist-c-0\">\r\n");
      out.write("            <div class=\"assist-c-1\">\r\n");
      out.write("                <div class=\"assist-c-1-1\">\r\n");
      out.write("                    <span>友情链接：</span>\r\n");
      out.write("                    <a href=\"#\">游戏交易平台</a>\r\n");
      out.write("                    <a href=\"#\">王者荣耀代练</a>\r\n");
      out.write("                    <a href=\"#\">海豹加速器</a>\r\n");
      out.write("                    <a href=\"#\">电竞饰品交易平台</a>\r\n");
      out.write("                    <a href=\"#\">新星饰品交易</a>\r\n");
      out.write("                    <a href=\"#\">交易代练通</a>\r\n");
      out.write("                    <a href=\"#\">游戏币交易平台</a>\r\n");
      out.write("                    <a href=\"#\">淘宝交易平台</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"assist-c-1-2\">\r\n");
      out.write("                    Copyright © 2018-2019 zuhaozhan233.com版权所有 ICP证：渝B1-20110004-10(重庆XXXX网络科技股份有限公司) 渝网文[2018]2034-030号\r\n");
      out.write("                    <img class=\"img-fluid\" src=\"img/sy_public_wpolic.gif\" alt=\"\">渝公网安备 31010202010327号\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- bottom e -->\r\n");
      out.write("<!-- model s -->\r\n");
      out.write("<!-- 模态框（Modal） -->\r\n");
      out.write("<div class=\"modal fade\" id=\"loginTipModel\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h4 class=\"modal-title\" style=\"color:deepskyblue;\">信息提示！</h4>\r\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body model-color-0\" style=\"color:red;\">登录失败，请重新登录！</div>\r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\">确定</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div><!-- /.modal-content -->\r\n");
      out.write("    </div><!-- /.modal -->\r\n");
      out.write("</div>\r\n");
      out.write("<!--model e -->\r\n");
      out.write("</body>\r\n");
      out.write("<!-- jquery-3.2.1.min.js 引入JQ -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<!-- bootstrap.bundle.min.js 用于弹窗、提示、下拉菜单 -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<!-- bootstrap.min.js 核心库-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- zhz233-home.js 核心库-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/zhz233-login.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
